[project]
name = "crawl-hdc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "aiohttp>=3.11.11",
    "crawlee[all]>=0.4.5",
    "python-dotenv>=1.0.1",
]
